//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apartments
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int IDCity { get; set; }
        public string Name { get; set; }
        public int CountryIDCountry { get; set; }
        public int ApartmentIDApartment { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Apartment Apartment { get; set; }
    }
}
